<a href="https://colab.research.google.com/github/parth5757/ML-AI-Data_Science/blob/main/library/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a Python library used for working with arrays.

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(np.__version__)

2.0.2


Checkinb Type of an numpy array

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Let's create an ndarray

In [5]:
array = np.array((1,2,3,4,5))
print(array)

[1 2 3 4 5]


Dimensional Array: level of array depth

Let's Start with 0-D array

In [6]:
arr = np.array(42)
print(arr)

42


Now let's see how 1D array is look like

In [7]:
arr =np.array([1,2,3,4,5])
print(arr)
# accessing the array elemet
print(arr[2])
print(arr.ndim)

[1 2 3 4 5]
3
1


Here the 2-D Array. It show in 2*2 matrix form. Let's see by following examples.

In [8]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
# way to access the 2d array element
print(arr[0,1])
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2
2


Here the 3-D Array. It show in 3*3 matrix form. Let's see by following examples.

In [9]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr)
# way to access the 3d array element
print(arr[0,1,2])
print(arr.shape)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
(2, 2, 3)
3


numpy.array_name.ndim is use to check the dimension of the array

In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


Accessing the element of the numpy array

In [30]:
arr = np.array([1, 2, 3, 4])
# 1-D Array
print("1-D arry elemets accessing:",arr[0])
# 1-D Array Negative indexing
print('Last element from 1nd dim: ', arr[-1])
print("addition of array elemets:", arr[2] + arr[3])
# 2-D Array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2-D arry elemets accessing:", arr[0,4])
# 2-D Array Negative indexing
print('Last element from 2nd dim: ', arr[1, -1])
#3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3-D arry elemets accessing:", arr[0,1,2])
print("3-D arry elemets accessing:", arr[-1,-1,-1])

1-D arry elemets accessing: 1
Last element from 1nd dim:  4
addition of array elemets: 7
2-D arry elemets accessing: 5
Last element from 2nd dim:  10
3-D arry elemets accessing: 6
3-D arry elemets accessing: 12
