<a href="https://colab.research.google.com/github/parth5757/ML-AI-Data_Science/blob/main/library/numpy_deep_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 1D Array

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2D Array

In [3]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
a = [1,2,3]
b = [4,5,6]
result = []

for i in range(len(a)):
  result.append(a[i] + b[i])
print(result)


# now with numpy
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)

[5, 7, 9]
[5 7 9]


### Array Properties

In [5]:
arr = np.array([[1,2,3], [4,5,6]])

In [6]:
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(np.zeros((3,4)))
print(np.ones((3,4)))
print(np.random.rand(3,3))
print(np.arange(0,10,9))
print(np.linspace(0,1,5))

2
6
(2, 3)
int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.57862849 0.22446684 0.69242893]
 [0.99774581 0.88952057 0.48350478]
 [0.21387926 0.92268793 0.40594993]]
[0 9]
[0.   0.25 0.5  0.75 1.  ]


### indexing & slicing

In [7]:
# 1d indexing
arr = np.array([10, 20, 30, 40])
print(arr[2])
print(arr[0:2])
#2d indexing
arr = np.array([[1,2,3], [4,5,6]])
print(arr[1,2])

30
[10 20]
6


### Mathemtical Operation

In [8]:
a = np.array([1,2,3])
print(a*2)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

[2 4 6]
21
3.5
6
1
1.707825127659933


### Broadcasting

In [9]:
a = np.array([1,2,3])
b = 5
print(a+b)

[6 7 8]


### Reshaping

In [10]:
arr = np.arange(6)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

### Practice Task

#### Task 1
Create array from 1 to 20 and reshape to 4x5.


In [11]:
arr = np.arange(20)
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Task 2

#### Create a 3x3 random matrix and find:

In [12]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
# print(arr.reshape(3,3))
print(arr)
print(arr.mean())
print(arr.max())
print(arr.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
9
45


### Task 3

#### Add 10 to every element of given arr

In [13]:
arr = np.array([5,10,15,20])
b = arr + 10
print(b)

[15 20 25 30]


### Task 4
#### Indexing

In [14]:
# Fancy Indexing

arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

# Boolean Indexing
arr = np.array([5,10,15,20,25])
print(arr[arr > 15])

[10 30 50]
[20 25]


In [15]:
# Modifying value using condition
arr = np.array([5,10,15,20])

if(arr[arr>15]):
  arr[arr<15] = 0
print(arr)

[ 0  0 15 20]


In [16]:
# Copy V/S View
arr = np.array([1,2,3,4,5])
slice_part = arr[0:4]
slice_part[0] = 99
print(slice_part)


# copy arr
copy_arr = arr[1:4].copy()
print(copy_arr)

[99  2  3  4]
[2 3 4]
